version: '3.8'

services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    ports:
      - '8800:8800'
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - '6500:5432'
    volumes:
      - excel_egde_postgres_db:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - excel_egde_redis_db:/data

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  excel_egde_postgres_db:
  excel_egde_redis_db: