version: '3.8'

services:
  app:
    container_name: exceledge-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8800:8800"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: sh -c "npx prisma migrate deploy && npm run dev"

  postgres:
    image: postgres:latest
    container_name: exceledge-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: excel_edge_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: exceledge-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
